const ACTION_TYPES = {
    //Hero
    CREATE_HERO_REQUEST: 'CREATE_HERO_REQUEST',
    CREATE_HERO_SUCCESS: 'CREATE_HERO_SUCCESS',
    CREATE_HERO_ERROR: 'CREATE_HERO_ERROR'
    //Power
    }
    
export default ACTION_TYPES