const ACTION_TYPES = {
    //Hero
    CREATE_HERO_REQUEST: 'CREATE_HERO_REQUEST',
    CREATE_HERO_SUCCESS: 'CREATE_HERO_SUCCESS',
    CREATE_HERO_ERROR: 'CREATE_HERO_ERROR',
    //GET_HEROES
   GET_HEROES_REQUEST: 'GET_HEROES_REQUEST',
   GET_HEROES_SUCCESS: 'GET_HEROES_SUCCESS',
   GET_HEROES_ERROR: 'GET_HEROES_ERROR'
    //GET_HEROES
    //Power
    }
    
export default ACTION_TYPES